config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get('/films', to: 'home#films')
  get('/directors', to: 'home#directors')
  get('/genres', to: 'home#genres')

  resources :films, only: [:show, :new, :create, :edit, :update]
  resources :genres, only: [:show, :new, :create, :edit, :update]
  resources :directors, only: [:show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre

  has_many :films
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :director
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def show
    @director = Director.find(params[:id])
    @films = @director.films
  end

  def new
    @director = Director.new
  end

  def create
    director_params = params.require(:director).permit(:name, :nationality, :birth_date, :genre_id)
    @director = Director.new(director_params)

    if @director.save
      return redirect_to root_path, notice: 'Diretor(a) cadastrado com sucesso.'
    end

    flash.now.notice = 'Diretor(a) não foi cadastrado.'
    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    director_params = params.require(:director).permit(:name, :nationality, :birth_date, :genre_id)

    if @director.update(director_params)
      return redirect_to director_path(@director.id), notice: 'Diretor(a) atualizado com sucesso.'
    end

    flash.now.notice = 'Diretor(a) não foi atualizado.'
    render :edit
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def create
    film_params = params.require(:film).permit(:title, :release_year, :synopsis, :country, :duration,
                                               :director_id, :genre_id)
    @film = Film.new(film_params)

    if @film.save
      return redirect_to root_path, notice: 'Filme cadastrado com sucesso.'
    end

    flash.now.notice = 'Filme não foi cadastrado.'
    render :new
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    film_params = params.require(:film).permit(:title, :release_year, :synopsis, :country, :duration,
                                               :director_id, :genre_id)

    if @film.update(film_params)
      return redirect_to film_path(@film.id), notice: 'Filme atualizado com sucesso.'
    end

    flash.now.notice = 'Filme não foi atualizado.'
    render :edit
  end


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @films = @genre.films
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(name: params[:genre][:name])

    if @genre.save
      return redirect_to new_genre_path, notice: 'Gênero cadastrado com sucesso.'
    end

    flash.now.notice = 'Gênero não foi cadastrado.'
    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(name: params[:genre][:name])
      return redirect_to genre_path(@genre.id), notice: 'Gênero atualizado com sucesso.'
    end

    flash.now.notice = 'Gênero não foi atualizado.'
    render :edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def films
    @films = Film.all
  end

  def directors
    @directors = Director.all
  end

  def genres
    @genres = Genre.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_with model: director do |f| %>
  <div>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :nationality, "Nacionalidade" %>
    <%= f.text_field :nationality %>
  </div>
  <div>
    <%= f.label :birth_date, "Data de nascimento" %>
    <%= f.date_field :birth_date %>
  </div>
  <div>
    <%= f.label :genre_id, "Gênero favorito" %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Edtiar diretor(a)</h1>

<%= render partial: 'form', locals: {director: @director} %>

app/views/directors/new.html.erb
<h1>Registro de diretor(a)</h1>

<%= render partial: 'form', locals: {director: @director} %>

app/views/directors/show.html.erb
<h1>Diretor(a): <%= @director.name %></h1>

<%= link_to("Editar", edit_director_path) %>

<div>
  <br/>
  <strong>Nome: </strong> <%= @director.name %>
  <strong>Nacionalidade: </strong> <%= @director.nationality %>
  <strong>Data de nascimento: </strong> <%= @director.birth_date %>
  <strong>Gênero favorito: </strong> <%= @director.genre.name if @director.genre %>
</div>

<div>
  <br/>
  <strong>Listando todos os filmes dirigidos por este diretor(a): </strong>
</div>

<% @films.each do |film| %>
  <div>
    <%= link_to film.title, film %>
  </div>
<% end %>

<br/>
<%= link_to("Voltar", directors_path) %>

app/views/films/_form.html.erb
<%= form_with model: film do |f| %>
  <div>
    <%= f.label :title, "Título" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_year, "Ano de lançamento" %>
    <%= f.number_field :release_year %>
  </div>
  <div>
    <%= f.label :synopsis, "Sinopse" %>
    <%= f.text_area :synopsis %>
  </div>
  <div>
    <%= f.label :country, "País de origem" %>
    <%= f.text_field :country %>
  </div>
  <div>
    <%= f.label :duration, "Duração (min)" %>
    <%= f.number_field :duration %>
  </div>
  <div>
    <%= f.label :director_id, "Diretor(a)" %>
    <%= f.collection_select :director_id, Director.all, :id, :name %>
  </div>
  <div>
    <%= f.label :genre_id, "Gênero" %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Edtiar filme</h1>

<%= render partial: 'form', locals: {film: @film} %>

app/views/films/new.html.erb
<h1>Registro de filmes</h1>

<%= render partial: 'form', locals: {film: @film} %>

app/views/films/show.html.erb
<h1>Filme: <%= @film.title %></h1>

<%= link_to("Editar", edit_film_path) %>

<div>
  <br/>
  <strong>Ano de lançamento: </strong> <%= @film.release_year %>
  <strong>Sinopse: </strong> <%= @film.synopsis %>
  <strong>País de Origem: </strong> <%= @film.country %>
  <strong>Duração (min): </strong> <%= @film.duration %>
  <strong>Diretor(a): </strong> <%= @film.director.name if @film.director %>
  <strong>Gênero: </strong> <%= @film.genre.name if @film.genre %>
</div>

<br/>
<%= link_to("Voltar", films_path) %>

app/views/genres/_form.html.erb
<%= form_with model: genre do |f| %>
  <div>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editar genêro</h1>

<%= render partial: 'form', locals: {genre: @genre} %>

app/views/genres/new.html.erb
<h1>Registro de genêro</h1>

<%= render partial: 'form', locals: {genre: @genre} %>

app/views/genres/show.html.erb
<h1>Gênero: <%= @genre.name %></h1>

<%= link_to("Editar gênero", edit_genre_path) %>

<div>
  <br/>
  <strong>Listando todos os filmes do gênero: </strong> <%= @genre.name %>
</div>

<% @films.each do |film| %>
  <div>
    <%= link_to film.title, film %>
  </div>
<% end %>

<br/>
<%= link_to("Voltar", genres_path) %>

app/views/home/directors.html.erb
<section id="directors">
  <h2>Lista de diretores</h2>

  <% @directors.each do |director| %>
    <div>
      <%= link_to director.name, director %>
    </div>
  <% end %>

  <br/>
  <%= link_to("Voltar", root_path) %>

</section>

app/views/home/films.html.erb
<section id="films">
  <h2>Lista de filmes</h2>

  <% @films.each do |film| %>
    <div>
      <%= link_to film.title, film %> - <%= film.release_year%>
    </div>
  <% end %>

  <br/>
  <%= link_to("Voltar", root_path) %>

</section>

app/views/home/genres.html.erb
<section id="genres">
  <h2>Lista de gêneros</h2>

  <% @genres.each do |genre| %>
    <div>
      <%= link_to genre.name, genre %>
    </div>
  <% end %>

  <br/>
  <%= link_to("Voltar", root_path) %>

</section>

app/views/home/index.html.erb
<section id="films">
  <h1>Gerenciar cadastros</h1>

  <nav>
    <li>
      <%= link_to "Filmes", films_path %>
    </li>
    <li>
      <%= link_to "Diretores", directors_path %>
    </li>
    <li>
      <%= link_to "Gêneros", genres_path %>
    </li>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmCatalogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <main>
      <div>
        <%= flash.notice %>
      </div>

      <nav>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Cadastrar novo filme", new_film_path %>
        </li>
        <li>
          <%= link_to "Cadastrar novo diretor(a)", new_director_path %>
        </li>
        <li>
          <%= link_to "Cadastrar novo gênero de filme", new_genre_path %>
        </li>
      </nav>
    </main>

    <%= yield %>
  </body>
</html>